### ISSUE TITLE
No LocalStability.h

### ISSUE THREAD

**Issue by jingchangshi** [vassilikitsios/local_linear_stability_cpp#1]
I compiled this version of codes and found a problem.

```
main.cpp:26:28: fatal error: LocalStability.h No such file or directory.
```

And indeed I found that there is not such file named "LocalStability.h".

Please provide such file.

Thanks!

P.S. I'm stuck with linear stability computation on Blasius boundary layer. I've already coded a shooting method and a spectral collocation method, which is successful on Poiseuille flow case. However, when applied on Blasius case, both codes failed.

Although I'm not able to capture the key point to correct my codes, I really want to get and test a piece of codes succefully working on Blasius case. Then I will study this codes and find out why my codes fail. So, I really hope to test your codes.

In fact, I test your Python version of this codes. However, I found that the output is not consistent with your PhD thesis. I've no idea what I missed when running your Python code.

Without any modification, Python version of this code gives following output on wave speed.

![wave_speed kxr0001 kxi0001 kzr0001](https://cloud.githubusercontent.com/assets/9106886/8847814/edff7b74-3164-11e5-85b9-f744c9d831d4.png)

**Comment by desperadoshi** [comment]
Oh, I forget to say that given Re = 998, Alpha = 0.308 for Blasius case, there is an unstable mode, c_{i} = 0.00795979 > 0. However, from the output, there is no such mode.

In your PhD thesis, such mode exists.

![Uploading 捕获.JPG…]()

**Comment by jingchangshi** [comment]
Oh, I forget to say that given Re = 998, Alpha = 0.308 for Blasius case, there is an unstable mode, c_{i} = 0.00795979 > 0. However, from the output, there is no such mode.

In your PhD thesis, such mode exists.

![1](https://cloud.githubusercontent.com/assets/9106886/8847911/de4bc4ca-3165-11e5-822d-5df3bc9b55d3.JPG)

**Comment by vassilikitsios** [comment]
In the python version of the code I have not yet implemented the ODE to calculate the true Blasius boundary layer, but I use an approximation that is typically used as an initial condition for solving the ODE, as I do in the c++ version. This is presumably the difference. In my PhD thesis I used the C++ version of the code.

In the makefile in the local_linear_stability_cpp/src/libLocalStability directory you'll notice that the header file LocalStability.h is produced by concatenating together all of the header files in the local_linear_stability_cpp/src/libLocalStability directory

So just make sure you make the libraries first before you make the drivers. That should produce all the necessary header files.

Let me know if you have any further problems.
